language: python

python:
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install -r requirements.txt -r requirements-dev.txt

env:
  global:
  - PYPI_USER_NAME: "chaostoolkit"
  - secure: "izU/NIXVzran5ax/0Y+mabjbioIhw468ZkRRwoWehVyRYVrizr3oWJlqrmjC5hpvLMyTtWF/2I+vQtyUR9uqGEwaDaNDgN5uGknZp7SS3e716cpGhpWUzJmDuLDjFD2m3VRluHOU7by35EebTDa741397KkzkMePrFErt1ce5wKmkmVpjRlfE90McHzy7zhmex8jrE+S2qtwvCA3ehcH7B4saFfE8uxG/BWfnZbrRA+rN/e3KWbybPX04KZmNy8tHPr1uNmKGqjKehZM9ntdnVaLr/XJDl/pOubF14ldb135Hdo3E51It1EtcgoXHxVswDA+W+I6B4J5xkA0Sp6EbWYWGOaXfeBcWsk0/1l34SLyDMovZasD1VPh8k7Ow3ghytAHSR4r3/XP15CXCbokz1oadHKZejirnSukWnaN5SpJT7/XiqLRg2HZBOpG8BooJAs5PcAHMfmXUVqbKg65EguhEJLiC3X0zlPNqgHh6/d/mVmwwdUMAEBoD9F3QMT0E1Hrv131ldGVYHTG/CQeWfPsO/M+ve+k4Ghj6lJ7kRrzBFIVStVLbwinEVWWBR/EPHpZ9/EAd8QdAKWVWhNylvqQj7XhVJAYvRJFdsIhCBN6xYnRE6AFaHOGI+8rp7OoZ3k10IMJKvWfH5FjvUpZeHJA8v7rOA1C9U4mnkvZHO8="
  - secure: "TqyIBBnlFA9fAKCX8HgambBwXIKvxeuWyQ/U7OovsxR0JgCMuOUez2Aw6xbMdnWsgaysdL6IdZZq2FzmbrLlA7hsgdUvq/mJ3/RccrFJ9myyaquuVjBiJ8vqbrTk2532aSQ0dD+itxdfzFZwU5mawORpPtjaVd8bOJC8l/qU886Y1DCpqEzwhGk5jlCS1iFHhXC08XI4UENJaVTtkOKQxX/FKPXQjIdUFsoXmbGpxJ1W73UuX4yX/dy5MXE1J5W/NpuMQufQtBLRWyVn0VUrG14zkgaKW+MTaJPa5X+IVjGQUpPj42OhHsnK9aqxoCyBbJSsHNPxME5OabSGmAqLio2O6i2X68FjSksRzw6PTl2KhWl40wThE4iSxr6Nzk3Y4HHSWQpLV6P5h4RCAsZDHDHPycH+uf+bJMnbGLo3wwXE4gv0v0s32q9vUBu0SO9zoDzuU5aCDqR/WnwmzkRnDzfn3O5EPCRsAHSqi2LsNC8GncvVnet/iAj1v+MR13sxx9OY5R67cyYsUJJdq1NI6xXoHCcLTYiwOcoYRfJ/yToOKilw4s3NWH1lcSj9JgnmNNeedcMbfxZMI4Ub3S2ZgqtO62fhrcGSWSHslPtskGox7inIsxXKw9wG7hqE5swEwT2U+yQZL3aQfZZnGTJ+FZo0qQhGHILCuuoymLYoe9I="
  - secure: qkiM9kjUqdZfy3bbDsDTzBMGh8o084HYIZ1bpUiJoDOVSkdIZ9jf8CKRh75zXcJ2naggS4XKiDpp1hmhlJfDTA+LbWkAw8bPCPAuQqCeySkPAbtL3S0Z8D4rp5+hLOgRg7xE8v1n3g4qMJwHGYC2gCScLNsmQfEFv0Ps/lV/NgzoSYi4Ur+RySus+IJadPVqd0ehxGPWGzRr7COkhtbDQiz29wqzsKbf9aBa0SGFwF0h4FPLbR+4hWCd1/3NHyqVwtoI+ufjsn2vKEV+h/R2Co0drLyObt+7AlEEbG58Y4ilNGymzKm2aEDbhpHmAvhXdNKB98DeYDGIaiqHm8ei82Z4CmS8tAAsXz2NFIh7NdUu1P+cK8uYqSAmGn7VglWYXZCuZ4iNGSqsl8aAXDO+H1+e8UuX+w/yoQj9VMSvjY4Oo6O4xrSUlnsAR2qCtN9YHGX8dTe4CyPdYw7W+yQHRPD6fUnr8j0/0ZrWdTSwNE43qbebNCi7zlrrGdrtIVaIzs4nwh3XX15v40E8CJxmdmZ4TQYf984wqeMhqIueX/66D9OQxXX5nRqSTAaXFPLSaFDZJZsroZxRaZbpe8ShTmJmFzkHl6Rfc6u6rekzlQKscO1ZDdhrdi3UPuK++H5/YvrxtQQDsuSlz84y54ijJqqa1dzd7MX/OIPUGyBD7l8=

script: 
  - bash ci.bash
notifications:
  webhooks:
    urls:
    - 'https://webhook.atomist.com/atomist/travis/teams/T76U4GPGF'
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always
