language: python

python:
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install -r requirements.txt -r requirements-dev.txt

env:
  global:
  - PYPI_USER_NAME: "chaostoolkit"
  - secure: "qkiM9kjUqdZfy3bbDsDTzBMGh8o084HYIZ1bpUiJoDOVSkdIZ9jf8CKRh75zXcJ2naggS4XKiDpp1hmhlJfDTA+LbWkAw8bPCPAuQqCeySkPAbtL3S0Z8D4rp5+hLOgRg7xE8v1n3g4qMJwHGYC2gCScLNsmQfEFv0Ps/lV/NgzoSYi4Ur+RySus+IJadPVqd0ehxGPWGzRr7COkhtbDQiz29wqzsKbf9aBa0SGFwF0h4FPLbR+4hWCd1/3NHyqVwtoI+ufjsn2vKEV+h/R2Co0drLyObt+7AlEEbG58Y4ilNGymzKm2aEDbhpHmAvhXdNKB98DeYDGIaiqHm8ei82Z4CmS8tAAsXz2NFIh7NdUu1P+cK8uYqSAmGn7VglWYXZCuZ4iNGSqsl8aAXDO+H1+e8UuX+w/yoQj9VMSvjY4Oo6O4xrSUlnsAR2qCtN9YHGX8dTe4CyPdYw7W+yQHRPD6fUnr8j0/0ZrWdTSwNE43qbebNCi7zlrrGdrtIVaIzs4nwh3XX15v40E8CJxmdmZ4TQYf984wqeMhqIueX/66D9OQxXX5nRqSTAaXFPLSaFDZJZsroZxRaZbpe8ShTmJmFzkHl6Rfc6u6rekzlQKscO1ZDdhrdi3UPuK++H5/YvrxtQQDsuSlz84y54ijJqqa1dzd7MX/OIPUGyBD7l8="
  - secure: "fdMjc6BGDJaNQ2OcwBqnTCicWufSK0vjToc7tbrgfGr+1+VEnu1w1DHny+1J0Iffj/+2X0bqewOzHdfDVZEsu/Vr2hmMtFSSNSMqrW9jScSP2KXmvGx86+BkXAJM82zN1jDwZ39DaH7t9BXUcUC4UALw9td8tkXPo6LGTWJWRM0yLuN/oPhBsvrJYjxOgWpcT5RmAcJvUAeLiO4vP2XcXHGNLBE4vmWRTMLidIJCwtRQqEX2Ui9daK+HV0B7njGvQKi1ykUGj2FoqZ4+LDk0t3kL/OHVQH3UuBlFzXG+EMzZUrMnK0wWYLhSpC0lgmiQLPEL7bunR/CoTm3pv2ytcdZERTvzRsK4AlD/byCTQx3L4QU10UnGSU5AIAdRJ7CK+ZLF4x83uq94gtInkY8AMHykKGqRSaywqBsT4tGc0asuFBK61CeglCHl3+T2SjNYhD08LyEJYtSyoHodWNntnhZyydNQp8nEiTeyKi4J7ApGjdj374wcFskwyvVKHc+NEIE/cfqYVx3mN7WxsJ5dizSwbGTUJRuCdMer7rJgxxzKw4ycqF0hx6BlmL/d0YJVT651/XeMsi+11bZsMLzwEGldHjbOEKvG6EdyFPFzEYvMwUspoH3mP1hKUEFor0+OkcsRL2TbwcMEm4eOVKlJ0H3hUmQQkjqeXQdNn6MRtAs="
  - secure: "pTnid7Va1D2aYd65bCyUqXqgili4iOjMbwGivxIp7hFOAcqb3ZQrcrWTxELC7UiYyD70/Ft2q5FiK4+YPbLC45rrl26tejl3u8P7G6ecF64Px0vqBQFRCdqh9myyBbD3pDPn5RlM3k+fniUl70sGGbcyV9WArqnwSNKw0VLtLoYl1WFflaaLTuPeKFJUVP3rn1yctKkk1BTMGb9ISJqqlqm1G+qC4GewrrGj1YTumTcOL28fCleGv4iiy0W7EGT0ET0xhavP5jnJSVubOL8c40x9gXSO4tGw23ixNAw9IAYYey9VTobTZvd5V+FQKAEkZiiuiDq/kDab18TkUvp0Ii0sYM9H7LYZYp9qernJtHlOkRVV3ldDEHZegX3x/c4QC6M3SkeUYr0PM7rqLLrLJJ4V4XsC1Gorwnc0n1R3et4Z/s/Ii2f5MG60xPSU/H96JwenIdOwHtQlxhExKRTls2GL4AL+m3PODKf8Z+tR7KaUyNNRnMsfRcaapLkFYlqfiQXByltnN+06EfctsZTve2/cemk5Q6Mv8sa7ihRPLvCc0CgDHk1Dqi3dzRSHLIw33oxwRWNsmboxp3yetnk2rjNMN9dBGevwEYS8dO9bX4dSbOHUSSsC2VS3eSSQiVCNttP1qxspXjIexmaQqT+KPrDDCRbv1YPVmOgK6d4pUXw="

script: 
  - bash ci.bash
notifications:
  webhooks:
    urls:
    - 'https://webhook.atomist.com/atomist/travis/teams/T76U4GPGF'
    on_cancel: always
    on_error: always
    on_start: always
    on_failure: always
    on_success: always
